# Generated by Django 4.2.7 on 2023-12-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('avaliable_ram', models.IntegerField()),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
